### ISSUE TITLE
Only 1 Image

### ISSUE THREAD

**Issue by flexer1886** [rxcle/rxindi#3]
Hello,

if I use this code, then unfortunately only 1 picture comes up, unfortunately it doesn't copy the picture frame. Can I adjust something there?

${*Sheet/Row}
**Image Frame**
${=/Root/Sheet/Row[7]/Picture,ProfilePic} 
${=/Root/Sheet/Row[7]/Name}
${.}

My Output is:

Image
Name
Name
Name
Name 
...

I want
Image
Name
Image
Name
...

Can you help? :)

Thank you

**Comment by rxcle** [comment]
In order to get the correct output for every row, the correct syntax would be
```
${*/Root/Sheet/Row}
Image Frame
${=Picture,ProfilePic}
${=Name}
${.}
```
This yields the following result:
![image](https://user-images.githubusercontent.com/48733400/225113339-dfdce8cc-d52c-41a5-83ef-3aca3aff6198.png)

Unfortunately I can confirm that in this case only the first image frame will be filled. The reason for this is that on every iteration in the loop a new image frame is created - however every image frame has the same name as the original frame (ProfilePic), so when setting the output, multiple frames with the same name are found and in this case the first one is selected to be filled.
![image](https://user-images.githubusercontent.com/48733400/225115300-a4b7c49b-2be7-434c-ad40-4e61113dd9c4.png)
One way to work around this in the current version is to have a small helper script that renames the frame automatically after placing an image in it. So that in the next iteration only a single frame exists with the target name.
![image](https://user-images.githubusercontent.com/48733400/225118289-b669c085-8108-4b17-a9bf-a555ae83f95e.png)

```
${*/Root/Sheet/Row}
Image Frame
${=Name}
${=Picture,ProfilePic}
${&RenameFrame,ProfilePic,string(@rxc-index)}
${.}
```
For this to work create a script file called "RenameFrame.jsx" (you can choose a different name, as long as it matches with the &reference name) in the same directory as the InDesign template document and in it place the following: 
```
scriptArgs.target.name = scriptArgs.params[0]
```
Hopefully this resolves your issue for now.

We'll add an issue to our backlog to investigate a way to make the expected behavior work in more obvious and user friendlier way in a future release.

**Comment by flexer1886** [comment]
Thank you! This is really such a big help.
