### ISSUE TITLE
[1.3.1] Component contents is not deleted when document is processed

### ISSUE THREAD

**Issue by bdno86** [rxcle/rxindi#7]
When I create a component that solely consists of a table, the component itself is not removed when Rxindi is run. This is consistent with what happens when you select a table and press backspace, which leads to the table contents being deleted but the table remaining.

When using:
<img width="1238" alt="image" src="https://github.com/rxcle/rxindi/assets/1181888/afe09b7c-cadd-4a99-b0b5-75d13c7fc7dd">

it Leads to:
<img width="1194" alt="image" src="https://github.com/rxcle/rxindi/assets/1181888/16c56156-5648-462e-94d7-8b36d9753603">

**Comment by rxcle** [comment]
Good find! 
The documentation explicitly states that component definitions are removed after processing, but seems like they actually aren't (or rather it's contents isn't) - it's not just tables either, this seems true for any component contents. So either the documentation was never correct or this got broken somewhere along the way and slipped through the regression tests. In any case this should probably be fixed because there is not much use in keeping components after a processing pass.

Luckily there is a relatively simple workaround for this: Move the component definition to a separate frame which is either off-page or on a hidden layer (the declaration and reference need not be in the same frame).

I'll mark this as a bug so it will be looked into for a future release.
